package GUI;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author judith
 */
import DB.Budget;
import DB.BudgetHasMaterial;
import DB.Material;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable.PrintMode;
import javax.swing.table.DefaultTableModel;


public class Form_Devis extends javax.swing.JFrame {
     
        
    /**
     * Creates new form Form_Devis
     */
    private int prixTotal = 0;
    private int index=1;
    private  int IdBudget = 0; 
    private int clic = 0;
    private int selectIndex;
    
    
    //variale du model 
    private BudgetHasMaterial budgetMaterials;
    private int IdMaterial;
    
    //model
    private ArrayList<Material> materials;
    public Form_Devis() {
        
        initComponents();
        this.setTitle("Gestion Devis");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Creation des Desvis");
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        this.IdBudget = new Budget().genere();
        this.jLabel6.setText(""+this.IdBudget);
        
        //paremetrage du tableau
        this.jTableDevis.getTableHeader().setFont(new Font("Tahoma",Font.BOLD,18));
        
        //this.jTableDevis.getTableHeader().setSize(null);
        this.jTableDevis.setFont(new Font("Tahoma",Font.BOLD,16));
        this.jTableDevis.setRowHeight(this.jTableDevis.getRowHeight()+20);
        
         //lecture des materiels
        this.materials = new Material().ReadMaterials();
        this.jComboBoxDesignation.removeAllItems();               
        this.materials.stream().forEach((Material material) -> {
            this.jComboBoxDesignation.addItem(material.getDesignation());
            
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPU = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldTVA = new javax.swing.JTextField();
        jTextFieldQt = new javax.swing.JTextField();
        jButtonInserer = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonDelete = new javax.swing.JButton();
        jComboBoxDesignation = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDevis = new javax.swing.JTable();
        jButtonPrint = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButtonNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204), 2), "Formulaire", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 153, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Designation ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Quantité");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("P.U");

        jTextFieldPU.setEditable(false);
        jTextFieldPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("T.V.A");

        jTextFieldTVA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTVA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTVAActionPerformed(evt);
            }
        });

        jTextFieldQt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonInserer.setBackground(new java.awt.Color(0, 204, 204));
        jButtonInserer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonInserer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/modifier.gif"))); // NOI18N
        jButtonInserer.setText("Inserer");
        jButtonInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsererActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Numéro");

        jLabel6.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("jLabel6");

        jButtonDelete.setBackground(new java.awt.Color(204, 0, 0));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(51, 255, 255));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_delete.png"))); // NOI18N
        jButtonDelete.setText("Supprimer");
        jButtonDelete.setOpaque(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jComboBoxDesignation.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jComboBoxDesignation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBoxDesignation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDesignationItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jComboBoxDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPU, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldQt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonInserer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldTVA, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldTVA, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldPU, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonInserer)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldQt, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .addGap(30, 30, 30))))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2), "Devis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16), new java.awt.Color(0, 204, 204))); // NOI18N

        jTableDevis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "Designation", "Quantité", "P.U", "T.V.A", "P.T"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDevis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDevisMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDevis);
        if (jTableDevis.getColumnModel().getColumnCount() > 0) {
            jTableDevis.getColumnModel().getColumn(0).setMinWidth(40);
            jTableDevis.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableDevis.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableDevis.getColumnModel().getColumn(1).setMinWidth(300);
            jTableDevis.getColumnModel().getColumn(1).setPreferredWidth(350);
            jTableDevis.getColumnModel().getColumn(1).setMaxWidth(500);
            jTableDevis.getColumnModel().getColumn(2).setMinWidth(90);
            jTableDevis.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableDevis.getColumnModel().getColumn(2).setMaxWidth(150);
            jTableDevis.getColumnModel().getColumn(3).setMinWidth(90);
            jTableDevis.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableDevis.getColumnModel().getColumn(3).setMaxWidth(200);
            jTableDevis.getColumnModel().getColumn(4).setMinWidth(100);
            jTableDevis.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableDevis.getColumnModel().getColumn(4).setMaxWidth(200);
            jTableDevis.getColumnModel().getColumn(5).setMinWidth(150);
            jTableDevis.getColumnModel().getColumn(5).setPreferredWidth(200);
            jTableDevis.getColumnModel().getColumn(5).setMaxWidth(250);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
        );

        jButtonPrint.setBackground(new java.awt.Color(204, 255, 204));
        jButtonPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonPrint.setForeground(new java.awt.Color(0, 102, 102));
        jButtonPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/printer.png"))); // NOI18N
        jButtonPrint.setText("Imprimer");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jButtonBack.setBackground(new java.awt.Color(255, 153, 153));
        jButtonBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(102, 0, 102));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/fermer_32.png"))); // NOI18N
        jButtonBack.setText("Retour");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonNew.setBackground(new java.awt.Color(0, 255, 153));
        jButtonNew.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButtonNew.setForeground(new java.awt.Color(153, 153, 255));
        jButtonNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sauvegarder.gif"))); // NOI18N
        jButtonNew.setText("Nouveau");
        jButtonNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(268, 268, 268)
                        .addComponent(jButtonNew, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNew)
                        .addComponent(jButtonBack))
                    .addComponent(jButtonPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTVAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTVAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTVAActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        int choix = JOptionPane.showConfirmDialog(null,"\t Voulez vous vraiment abandonner ce devis ? \t","Retour",JOptionPane.YES_NO_OPTION);
        if (choix == JOptionPane.YES_OPTION){
            this.dispose();
            new Acceuil().setVisible(true);
        }
            
    }//GEN-LAST:event_jButtonBackActionPerformed
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

 public void print2(){
     
     //create a new budget
     Budget budget = new Budget();
     budget.setId(this.IdBudget);
     budget.setPrice(this.prixTotal);
     
     //sauvegarde dans la base de données 
    budget.Save();
    
     //insertion de la ligne du total 
        DefaultTableModel dt = (DefaultTableModel) this.jTableDevis.getModel();
        Object[] obj = {"","","","","Total",""+this.prixTotal};
        dt.addRow(obj);
     
     //impression
         PrinterJob job = PrinterJob.getPrinterJob();
         MessageFormat [] h = new MessageFormat[6];
         h[0] = new MessageFormat("                                     ");
         h[1] = new MessageFormat("                                                         PRINOBAT                 ");
         h[2] = new MessageFormat("                                  Maçonnerie - Carrelage - Plomberie - Electricité             ");
         h[3] = new MessageFormat("                                          Peinture - Dessin et conception");
         h[4] = new MessageFormat("                   Tél: 698 496 048 / 677 224 984 / E-mail: nonootchouanti@yahoo.fr");
         h[5] = new MessageFormat("                                     ");
         
         MessageFormat [] f = new MessageFormat[4];
         f[0] = new MessageFormat("___________________________________________________________________________________________");
         f[1] = new MessageFormat("                                 La solution pour vos travaux aux coûts les plus faibles          ");
         f[2] = new MessageFormat("                              Votre future maison clé sur la porte dans les délais prévus       ");
         f[3] = new MessageFormat("                                     ");
        
        job.setPrintable(new MyTablePrintable(this.jTableDevis, PrintMode.FIT_WIDTH, h, f));
        if (job.printDialog())
            try {
              System.out.println("Calling PrintJob.print()");
              job.print();
              System.out.println("End PrintJob.print()");
            }
            catch (PrinterException pe) {
              System.out.println("Error printing: " + pe);
            }
        
        new Form_Devis().setVisible(true);
        this.dispose();
     
 }
    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        // TODO add your handling code here:
        this.print2();
    }//GEN-LAST:event_jButtonPrintActionPerformed

    private void jButtonInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsererActionPerformed
        // TODO add your handling code here:
        
        if( !this.jComboBoxDesignation.getSelectedItem().toString().equals("") && 
            !this.jTextFieldPU.getText().equals("") &&
            !this.jTextFieldTVA.getText().equals("") && 
            !this.jTextFieldQt.getText().equals("")
           ){
            int prixt = Integer.parseInt(this.jTextFieldQt.getText())*Integer.parseInt(this.jTextFieldPU.getText());
            //create a new obect 
            this.budgetMaterials = new BudgetHasMaterial();
            
            this.budgetMaterials.setIdBudget(this.IdBudget);
            this.budgetMaterials.setTVA(Integer.parseInt(this.jTextFieldTVA.getText()));
            this.budgetMaterials.setIdMaterial(this.IdMaterial);
            this.budgetMaterials.setQuantity(Integer.parseInt(this.jTextFieldQt.getText()));
            this.budgetMaterials.setPrice(prixt);
            
            //save on the database
            this.budgetMaterials.Save();
            this.prixTotal += prixt;
            
            //insertion dans le table
            DefaultTableModel dt = (DefaultTableModel) this.jTableDevis.getModel();
            Object[] obj ={index,this.jComboBoxDesignation.getSelectedItem().toString(),this.jTextFieldQt.getText(),this.jTextFieldPU.getText(),this.jTextFieldTVA.getText(),""+prixt}; 
            index++;
            dt.addRow(obj);
            
            //reinitialisation du ormulaire
            this.jTextFieldPU.setText("");
            this.jTextFieldTVA.setText("");
            this.jTextFieldQt.setText("");
          
            
        } else {
            JOptionPane.showMessageDialog(null,"Veillez remplir le formulaire correctement "," Erreur: #006 ",JOptionPane.WARNING_MESSAGE);
        }   
        
    }//GEN-LAST:event_jButtonInsererActionPerformed

    private void jButtonNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNewActionPerformed
        // TODO add your handling code here:
        int choix = JOptionPane.showConfirmDialog(null,"Voulez vous vraiment abandonner ce devis?"," Abandonner",JOptionPane.YES_NO_OPTION);
        
        if (choix == JOptionPane.YES_OPTION){
            //delete all the ligne o the table BudgetHasMaterial that have as IdBudget this.num
            new BudgetHasMaterial().Delete(this.IdBudget);
             new Form_Devis().setVisible(true);
             this.dispose();
        }
    }//GEN-LAST:event_jButtonNewActionPerformed

    /**
     *
     */
    public void supprimer(){
    try{
    
        if(this.selectIndex != -1){
            DefaultTableModel dt = (DefaultTableModel) this.jTableDevis.getModel();
           
            if(new BudgetHasMaterial().Delete(this.IdMaterial, this.IdBudget) == 1 ){
                dt.removeRow(this.selectIndex);
            }
            
    } else {
        JOptionPane.showMessageDialog(null,"Veillez selectioner la ligne a suprimer","Erreur: #012",JOptionPane.ERROR);
    }
    }catch(Exception ex){
        JOptionPane.showMessageDialog(null,"Erreur: "+ex.getMessage(),"Erreur: #014",JOptionPane.ERROR_MESSAGE);
    }
    
    
}
    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        this.supprimer();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTableDevisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDevisMouseClicked
        // TODO add your handling code here:
        this.selectIndex = this.jTableDevis.getSelectedRow();
        if (this.selectIndex != -1){
             this.jButtonDelete.setEnabled(true);
        }else 
            this.jButtonDelete.setEnabled(false);
       
    }//GEN-LAST:event_jTableDevisMouseClicked

    private void jComboBoxDesignationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDesignationItemStateChanged
        // TODO add your handling code here:
        int selected = this.jComboBoxDesignation.getSelectedIndex();
        
         if (selected != -1){
             System.out.println(" INDEX "+selected);
             System.out.println(" designation "+this.materials.get(selected).getDesignation());
             this.jTextFieldPU.setText(""+this.materials.get(selected).getUnitPrice());
             this.IdMaterial = this.materials.get(selected).getId();
         }
        
    }//GEN-LAST:event_jComboBoxDesignationItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Devis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Devis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Devis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Devis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Devis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonInserer;
    private javax.swing.JButton jButtonNew;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JComboBox jComboBoxDesignation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDevis;
    private javax.swing.JTextField jTextFieldPU;
    private javax.swing.JTextField jTextFieldQt;
    private javax.swing.JTextField jTextFieldTVA;
    // End of variables declaration//GEN-END:variables
}
